version: "3"
services:
  websocket_server:
    container_name: event-reminder
    restart: always
    build: .
    environment:
      - PORT=3000
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=event_schedule
      - DB_USER=
      - DB_PASSWORD=
      - DB_AUTHSOURCE=
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"